[package]
authors = ["Jonah Hopkin <jonahhopkin@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "canadensis_mvp"
version = "0.1.0"

[dependencies]
# NOTE: stm32f1xx-hal should really re-export their version of bxcan
bxcan = "0.7.0"
canadensis = "0.3.3"
canadensis_bxcan = "0.3.1"
canadensis_can = "0.3.1"
canadensis_data_types = "0.3.2"
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
embedded-alloc = "0.6.0"
fugit = "0.3.7"
heapless = "0.7.17"
nb = "1.1.0"
panic-halt = "1.0.0"

[dependencies.stm32f1xx-hal]
version = "0.10.0"
features = ["rt", "stm32f103", "medium"]

[dependencies.cortex-m]
version = "0.7.7"
features = ["critical-section-single-core"]

# Uncomment for the panic example.
# panic-itm = "0.4.1"

# Uncomment for the device example.
# Update `memory.x`, set target to `thumbv7em-none-eabihf` in `.cargo/config`,
# and then use `cargo build --example device` to build it.
# [dependencies.stm32f3]
# features = ["stm32f303", "rt"]
# version = "0.7.1"

# this lets you use `cargo fix`!
[[bin]]
name = "canadensis_mvp"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
