version: "3.9"
services:
  ros2_docker:
    extends:
      file: docker-compose.yml
      service: ros2_docker
    network_mode: "host"
    tty: true
    ulimits:                  # Allow realtime privileges
      rtprio: 99
    cpu_rt_runtime: 200000
    cap_add:
      - ALL
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
