version: "3.9"
services:
  ros2_docker:
    extends:
      file: docker-compose.yml
      service: ros2_docker
    network_mode: "host"
    privileged: true          # Required for accessing hardware
    tty: true
    ulimits:                  # Allow realtime privileges
      rtprio: 99
    cpu_rt_runtime: 200000
    cap_add:
      - ALL
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev             # Required for accessing hardware
      - /dev/shm:/dev/shm     # Required for ROS 2 shared memory communication
      