controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    enforce_command_limits: true # true by default *after Jazzy*!

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
