on:
  push

jobs:
  check-boards:
    runs-on: alpine-latest
    defaults:
      run:
        working-directory: ./github/workflows
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Check PCB's 
        run: ./check_boards.sh
